buildscript {
    ext {
        kotlin_version = '2.1.0'
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.8.0'
    }
}

plugins {
    id("org.jetbrains.kotlin.jvm") version("$kotlin_version")
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

//task clean(type: Delete) { TODO Not sure what this is for...
//    delete rootProject.buildDir
//}
